name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Publish container
      id: publish
      uses: matootie/github-docker@v3.1.0
      with:
        accessToken: ${{ github.token }}
        tag: |
          latest
          ${{ github.sha }}
          
    - name: Print URL
      run: echo ${{ steps.publish.outputs.imageURL }}
